### ISSUE TITLE
Couldn't choose save location

### ISSUE THREAD

**Issue by StrangePigeon79** [Knightbomb8/Ascii-Art#1]
As the title says, I couldn't choose the folder to save the generated image.
Exit code: -1073740791 (0xC0000409)

After trying to run it in cmd it gives this error:

Traceback (most recent call last):
  File "C:\Users\gamer\Downloads\AsciiGUIElements.py", line 185, in <lambda>
    self.generate_art_button.clicked.connect(lambda e: self.set_generation_state(media_generator(
                                                                                 ^^^^^^^^^^^^^^^^
  File "C:\Users\gamer\Downloads\main.py", line 49, in generate_ascii_image
    successful_completion, data = self.ascii_image_gen.generate_ascii_image(path, 11 - quality, is_colored)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gamer\Downloads\ASCIIGenerators.py", line 181, in generate_ascii_image
    new_img = create_ascii_image(pic, quality, is_colored)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gamer\Downloads\ASCIIGenerators.py", line 38, in create_ascii_image
    char_width = font.getsize("x")[0]
                 ^^^^^^^^^^^^
AttributeError: 'ImageFont' object has no attribute 'getsize'

Do you know how to solve it?

**Comment by Knightbomb8** [comment]
Hmm, something must of changed. Im seeing the failure on my end too. Ill check this out and get back to you.

**Comment by Knightbomb8** [comment]
Sorry about the slow fix. It is good now. 

Pillow changed the way you get the size of characters. easy fix luckily

**Comment by Knightbomb8** [comment]
Lemme know if you have any suggestions

**Comment by StrangePigeon79** [comment]
Also, for the UI you could try to make it with Kivy. It looks cooler way cooler and more professional.
